name: pt
channels:
  - conda-forge
  - defaults
dependencies:
  - cycler=0.10.0=py36_0
  - editdistance=0.4=py36hf484d3e_1001
  - gettext=0.19.8.1=h5e8e0c9_1
  - isort=4.3.4=py36_0
  - libflac=1.3.1=hfc679d8_2
  - libgcc=7.2.0=h69d50b8_2
  - libogg=1.3.2=h470a237_1
  - libsndfile=1.0.28=hfc679d8_0
  - libvorbis=1.3.5=h470a237_1
  - pysoundfile=0.10.2=pyh14c3975_1000
  - setuptools=40.6.2=py36_0
  - six=1.11.0=py36_1
  - wheel=0.32.3=py36_0
  - astroid=2.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cffi=1.11.5=py36he75722e_1
  - dbus=1.13.2=h714fa37_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36hf484d3e_0
  - lazy-object-proxy=1.3.1=py36h14c3975_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=3.0.1=py36h5429711_0
  - mccabe=0.6.1=py36_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - olefile=0.46=py36_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py36h04863e7_0
  - pcre=8.42=h439df22_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=18.1=py36_0
  - pycparser=2.19=py36_0
  - pylint=2.2.2=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.6=h6e4f718_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py36hfa4b5c9_1
  - sip=4.19.8=py36hf484d3e_0
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.28.1=py36h28b3542_0
  - typed-ast=1.1.0=py36h14c3975_0
  - wrapt=1.10.11=py36h14c3975_2
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
prefix: /home/gaochangw/anaconda3/envs/pt

